# Generated by Django 2.0 on 2017-12-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20171215_2339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
